# Generated by Django 3.0.1 on 2020-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=12)),
                ('facebook_id', models.CharField(max_length=500)),
                ('google_id', models.CharField(max_length=500)),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(verbose_name='date published')),
                ('updated', models.DateTimeField(verbose_name='updated date')),
            ],
        ),
    ]
